// components/form/components/Dependency/index.tsx
import type { PropType } from 'vue'
import type { NamePath } from '../../typing'
import { computed, defineComponent } from 'vue'
import { useFieldContext } from '../../FieldContext'

function getValueByNamePath(model: Record<string, any>, name: NamePath) {
  const path = Array.isArray(name) ? name : [name]
  return path.reduce<any>((current, key) => current?.[key], model)
}

function setValueByNamePath(target: Record<string, any>, name: NamePath, value: any) {
  const path = Array.isArray(name) ? name : [name]
  const first = path[0]
  if (first === undefined)
    return
  if (path.length === 1) {
    target[first] = value
    return
  }
  const last = path[path.length - 1]
  if (last === undefined)
    return
  const parent = path.slice(0, -1).reduce<Record<string, any>>((current, key) => {
    if (!current[key] || typeof current[key] !== 'object')
      current[key] = {}
    return current[key]
  }, target)
  parent[last] = value
}

const ProFormDependency = defineComponent({
  name: 'ProFormDependency',
  props: {
    name: { type: Array as PropType<NamePath[]>, required: true },
  },
  setup(props, { slots }) {
    const fieldContext = useFieldContext()
    const values = computed(() => {
      return props.name.reduce<Record<string, any>>((result, item) => {
        setValueByNamePath(result, item, getValueByNamePath(fieldContext.model || {}, item))
        return result
      }, {})
    })

    return () => slots.default?.(values.value) ?? null
  },
})

export default ProFormDependency

// components/form/components/SchemaForm/valueType/dependency.tsx
import ProFormDependency from '../../Dependency'
import type { NamePath } from '../../../typing'
import type { ProSchemaRenderValueTypeFunction } from '../typing'

function normalizeDependencyNames(name?: NamePath[] | NamePath): NamePath[] {
  if (!name)
    return []
  if (Array.isArray(name) && Array.isArray(name[0]))
    return name as NamePath[]
  return Array.isArray(name) ? name as NamePath[] : [name]
}

export const dependency: ProSchemaRenderValueTypeFunction = (item, helpers) => {
  if (item.valueType !== 'dependency')
    return true

  const fieldProps = item.getFieldProps?.() || {}
  const names = normalizeDependencyNames(item.name || fieldProps.name)
  if (!names.length || typeof item.columns !== 'function')
    return null

  return (
    <ProFormDependency name={names as any} {...fieldProps} key={item.key as any}>
      {(values: Record<string, any>) => helpers.genItems((item.columns as any)(values))}
    </ProFormDependency>
  )
}
